spring.application.name=salestrack-crm
spring.datasource.url=jdbc:postgresql://localhost:5432/salestrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
